[versions]
agp = "9.0.0"
fmpp = "0.9.16"
freemarker = "2.3.34"
kotlin = "2.3.0"
#noinspection UnusedVersionCatalogEntry
android-minSdk = "24"
#noinspection UnusedVersionCatalogEntry
android-compileSdk = "36"
sonarQube = "7.2.2.6593"
ksp = "2.3.4"

[libraries]
fmpp = { module = "net.sourceforge.fmpp:fmpp", version.ref = "fmpp" }
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }
junit = { module = "junit:junit", version = "4.13.2" }
junit-params = { module = "pl.pragmatists:JUnitParams", version = "1.1.1" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
mockk = { group = "io.mockk", name = "mockk", version = "1.14.7" }



[plugins]
googleKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
kotlin-multiplatform-android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
sonarQube = { id = "org.sonarqube", version.ref = "sonarQube" }